"use strict";

var _assert = _interopRequireDefault(require("@dashkite/assert"));

var _amen = require("@dashkite/amen");

var _amenConsole = _interopRequireDefault(require("@dashkite/amen-console"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.5.1
(async function () {
  (0, _amenConsole.default)(await (0, _amen.test)("Genie Files", [(0, _amen.test)("todo")]));
  return process.exit(_amen.success ? 0 : 1);
})();
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QvaW5kZXguY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBQUE7O0FBQ0E7O0FBQ0E7Ozs7O0FBRUcsQ0FBQSxrQkFBQTtBQUVELDRCQUFNLE1BQU0sZ0JBQUEsYUFBQSxFQUFvQixDQUU5QixnQkFGRixNQUVFLENBRjhCLENBQXBCLENBQVo7U0FNQSxPQUFPLENBQVAsSUFBQSxDQUFhLGdCQUFBLENBQUEsR0FBYixDQUFBLEM7QUFSQyxDQUFBIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IGFzc2VydCBmcm9tIFwiQGRhc2hraXRlL2Fzc2VydFwiXG5pbXBvcnQge3Rlc3QsIHN1Y2Nlc3N9IGZyb20gXCJAZGFzaGtpdGUvYW1lblwiXG5pbXBvcnQgcHJpbnQgZnJvbSBcIkBkYXNoa2l0ZS9hbWVuLWNvbnNvbGVcIlxuXG5kbyAtPlxuXG4gIHByaW50IGF3YWl0IHRlc3QgXCJHZW5pZSBGaWxlc1wiLCBbXG5cbiAgICB0ZXN0IFwidG9kb1wiXG5cbiAgXVxuXG4gIHByb2Nlc3MuZXhpdCBpZiBzdWNjZXNzIHRoZW4gMCBlbHNlIDFcbiJdLCJzb3VyY2VSb290IjoiLi4ifQ==
//# sourceURL=/Users/dy/repos/dashkite/vedic-dolphin/.tempo/masonry-targets/test/index.coffee